name: Publish & Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC and GitHub Pages
  contents: write
  pages: write

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for provenance data generation

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup environment
        uses: actions/setup-node@v6
        with:
          node-version: '24.13.0'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Unit tests
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge-main-into-develop:
    name: Merge main into develop
    needs: publish-to-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Merge main into develop
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch
          git pull
          git checkout develop
          git pull
          git merge main -m "Merge main into develop [skip ci]"
          git push origin develop
